//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CatalogoPersonal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Persona
    {
        public int idPersona { get; set; }
        public string nombrePersona { get; set; }
        public string apellidoPersona { get; set; }
        public Nullable<int> edad { get; set; }
        public string email { get; set; }
        public Nullable<int> telefono { get; set; }
        public Nullable<System.DateTime> fechaNacimiento { get; set; }
        public string ciudad { get; set; }
    }
}
